# Change these first
owner: LDSupport # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Identity Server (Cloud-Hosted)
    url: https://ld-chat-u3y1tf.us1.zitadel.cloud/debug/healthz
  - name: Identity Server (Self-Hosted)
    url: https://auth.ldsupport.nl/debug/healthz
  - name: CoachYourself.online
    url: https://app.coachyourself.online
  - name: Dynamic Managing (Old)
    url: https://dynamicmanaging.com
  - name: Lite - Dynamic Managing
    url: https://lite.dynamicmanaging.com
  - name: Analyzer.global
    url: https://ld.analyzer.global
  - name: Chimera
    url: https://chimera.ldscc.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  apiBaseUrl: https://api.github.com
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
