# Change these first
owner: LDSupport # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Identity Server
    url: https://auth.ldsupport.nl/debug/healthz
  - name: CoachYourself.online
    url: https://app.coachyourself.online
  - name: Dynamic Managing (Old)
    url: https://dynamicmanaging.com
  - name: Lite - Dynamic Managing
    url: https://lite.dynamicmanaging.com
  - name: Analyzer.global
    url: https://ld.analyzer.global
  - name: Chimera
    url: https://chimera.ldscc.com

status-website:
  theme: light
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  apiBaseUrl: https://api.github.com
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://eq4wvga9qy9.exactdn.com/wp-content/uploads/2023/08/logo.svg
  name: L&D Support Products Status
  introTitle: "**L&D Support Products Status** is your comprehensive system health monitoring portal, providing real-time status updates for all our products and services."
  introMessage: This status page displays **live** health data for all L&D Support systems and services. Monitor uptime, performance, and availability across our entire product suite to stay informed about service status.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
